apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  # comments: urls for databases and eureka server
  # userdb_url: jdbc:mysql://localhost:3306/userdb
  # restaurantdb_url: jdbc:mysql://localhost:3306/restaurantdb
  # foodcatalogueadb_url: jdbc:mysql://localhost:3306/foodcataloguedb
  # orderdb_url: atlasurl@atlas-cluster.b3dwy1m.mongodb.net/
  # eureka_service_address: http://eureka-0.eureka-service:8761/eureka/
